services:
  app:
    container_name: this_is_the_gwei_app
    restart: always
    build: .
    ports:
      - 3000:3000
    external_links:
      - mongo
  db:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
